version: '3.3'

services:
  gs-connector:
    image: gulstream/gs-connector:latest
    command: postgres2kafka
    environment:
      GS_POSTGRES_CONNECTIONURI: postgres://root:root@postgres:5432/postgres?replication=database
      GS_POSTGRES_SLOTNAME: gulfstream
      GS_KAFKA_BROKERS: kafka:9092
      GS_KAFKA_CLIENTID: gulfstream-connector
      GS_KAFKA_RETRYMAX: 10
      GS_KAFKA_RETRYBACKOFF: 1s
      GS_KAFKA_REQUIREDACKS: local # waitForAll
      GS_KAFKA_MAXMESSAGEBYTES: 15000000
      GS_KAFKA_TIMEOUT: 10s
    depends_on:
      - postgres
      - kafka
    restart: always
    networks:
      - dev