version: '3.3'

services:
  kowl:
    image: quay.io/cloudhut/kowl:master
    ports:
      - 8082:8080
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
    restart: always
    networks:
      - dev
