version: '3.3'

services:
  postgres:
    hostname: postgres
    image: postgres:13.0
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "5435:5432"
    expose:
      - "5435"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - ./tmp:/data/postgres
      - ./configs/postgresql.conf:/etc/postgresql.conf
      - ./configs/gulfstream.sql:/docker-entrypoint-initdb.d/gulfstream.sql:ro
    networks:
      - dev
